version: '3.9'

# Kafka   = localhost:9092
# DepSvc  = http://localhost:8180/api/dependencies/

networks:
  mclaren-net:
    name: "mclaren-net"

services:
  dependency-server:
    image: 'mclaren-tap-docker-dev-local.jfrog.io/dependencies-service:2020.2.0'
    container_name: dependency-server
    networks:
      - mclaren-net
    ports:
      - '127.0.0.1:8180:8180'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mclaren-net
    ports:
      - "127.0.0.1:2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka:4.1.3
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - mclaren-net
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-init:
    image: confluentinc/cp-kafka:4.1.3
    container_name: kafka-init
    depends_on:
      - "kafka"
    networks:
      - mclaren-net
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REPLICATION_FACTOR: 1
    env_file:
      ./topics.env
    volumes:
      - ./:/app
    command: ["/app/wait-for-it.sh", "-t", "0", "kafka:9092", "--", "/app/init-kafka.sh"]

  